services:
  rag:
    build: .
    image: rag-container:latest
    ports:
      - 8000:8000
    environment:
      OPENAI_URL: http://litellm:4000
      QDRANT_URL: http://qdrant:6333
    depends_on:
      - litellm
      - qdrant
    profiles:
      - prod

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant/volume/:/qdrant/storage:z
    profiles:
      - infra
      - prod

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - 4000:4000
    volumes:
      - ./litellm-config.yml:/app/litellm-config.yml
    command: ["--config", "/app/litellm-config.yml"]
    env_file: .env
    environment:
      LANGFUSE_HOST: http://langfuse:3000
      REDIS_URL: redis://:myredissecret@redis:6379
    profiles:
      - infra
      - prod

include:
  - https://github.com/langfuse/langfuse.git
